travis:
  secure:
    BINSTAR_TOKEN: Y6bxMvrKjpiUV0XOyR5yQWODql1OIBGWt0dhSLmxuCfnMBXuqoRqvUEge83P+rcMEfRnc4wghmlruKzlgSlyRsw4r0Z1rP5yy5PLxZh4HnWorjiDOQHFMWP67elZNhNM9ukFrg4h6uXnwRIv/t4Vr8Wc8qcmqmIrvReq0kJfzlG5TO6yLMvAbvipnG7Phi+yeGJKmkgWvkcvi+QqPpyFDS7xA5oH3FSDml3KDiqgd6nHC43bcYdzpPjmB2uMCsNq0l30hxwlzXbOhbtfhR5gQBJmFEGXJU1wFIcNzdCXCarKY98ObhxwetjHHn2IYcKZhpWo6NJhaagW1ADPWx6aEI+1iX5akrgQNZMn50eDBMPZYg8ALkeFTkOMBV51WA8bhOFziwZvKeR9xZ5CFdlYSIrhMihyyGiq98CdtFebVyj5WUQF6Qcq47eSeNV9Y77pZEQafHYuyuJZdBl/COH1ktVo1VM1sl1UHqY5Vcm8lPlF02K/c4R48tGkIf97E5gs9VVavvXwjBfEZBRvbpk16zjXR1PsTyScxLXZVcRNHjPWd9pFMV2L+3CxXPqzU30/ED8RuOYT2fSz9pj6tF8hQPcLbUXJG9G/W4fY3lW6gAjkpfbl+7+nXUwLYOXSy9Fmrk+dDtZ6KFPLenrD17kZNNh8fhmfhr0WVsMN50ntck4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
