travis:
  secure:
    BINSTAR_TOKEN: RfGLwnfvxUvggCUb4gvAZJwYf2GfRCLzGxmqhjJkyzMD1ZZWL0K4FwjTS5oI7jTfqf7aH7OndoyNFDB8GRuSideaC36xJLsmJVVYnZcF8J95jLzXHF1UYUyG4iX3qxaC7lBHGtvZlOhtajaaKtnq5XilBzgn7lyXXRbOaaVb5kP8N4q13BDy3MysNivybrFHEb9bGS1NDos/+xlGLnJQddSyEmhjlNbcq+GsQD5gS11RvZOOeYMg1AMJ4d0/U+Q3EfPgAY6dZ8kEn/z9hDp8lTSAY+dSrfP1XZ2q65Is+WclU7Ci/L8QGhQ+HwD3fzjN32l8lCtRrLbLmFFMi9ci20f/714h+zKeN/Zx8VedbJEO7ER8SzcLWs0VjyTTPI7ys58AogqDj9Ne2w5eBxEmqYoe4tuzxxrQscJNQUsIovre91nm3WzhlxV1xY28A2Fy42dTRhm/uldt8jHqGFoeR6ONEJTkNYj468aGRKQwax2jUYpHyMuEt73hf17/dYfIl2TQMEQtYVDfPb9sRM4pbCsGo+auxsTigThazN9y7/YMffLpBchc4f3TNFRmdDOxhR1LMrm0fU3KUkYp+g6JikhvfWz5sBniNzZ7Xs8zHyar93Kl8Elju96RUlJiuCK45q4h+zJJm33+QtMWLj6hO+ugXZy6afU4zTukqDKX+8c=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
