travis:
  secure:
    BINSTAR_TOKEN: R0riC8IcgFfp60R46Op5MAXgP+EAUIshbqs51C8wcu4RW6vzBDrMK7dTdLN1d2nkHMNTYyaWwh2xO4ux/e8MKOcncAXtwh+4gGiN1xYpnW3x/IjQIXLPZ2WRGgMe48zRtn5lVvVjwXSmIW/XJpJXdCEvEk52QHs9BBJzbZncC7G7f5eYtPDHLpNXgQjllLZv6SMPZxrLCJfSWuaoBguC4bSIuZaersLJBXj7EMaNXF14b2KMiiKr0YRoh8l8E5rHSr0QNO2tQcMn0WFstLjdy2ChForPUw5H7ymCnjSaTthipilOWgTjr+r5uiDymPL4XnctSh5JtlPmtQBsNsFW8yyiZ6Zk4tjBHWloj65YPGJBqzwFofHLHDpfKYDYuJ+leSAWxr5PSYRaDX/cHi3c/4ZcLkZY0h1AFS0d3VUulxo71/hgOivvyp+wCtdAUISfBRKky6ARpBbXd/ppkdvdoDR9iHjrdcajA+ScKlPkqRW1FaX8png/vcV0MrEEdKC0Ciy/hFmWDlPEi1X2VxxN9Y4DGcUeo/UbMr5rE/33pzYITMdwpzrgv/7aYCQkUxwpsmgyAAV5uXaRubcGpUci4EXht/pn9Nq4kM8a2dhzLeWwCuLkIIahD0qJNfKkWolW6teqmtZd2miNhWzADA3l8u2k796PRIWvryynoTj4m1U=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
