travis:
  secure:
    BINSTAR_TOKEN: StSd9ulp6QlIuRaySVKyqug0qZTNvG1q20wEiEWKS40GdjIYt9xd3PXD31bgiX/KDZiLBiXkQgdJN42J7I32AY7zv7KFGul322m3eUhmAiq0MhKraR7EJt/iBBAGGaEDkrH8KkAz6Gor1x3Hlf3X9a/12UK7JBIGzmY3yawXtfDX2fDIkbu5SZkUi1agfmtG6PmX0ROxsXkG8pibaQuE2DFSwHX6jZkOVmbIKwshVcXis0JAHB4vbRcp4s2GY/zD130sayAN1MvUighy18QnM66sTpgeesAc85hmflutKwKXJOwfH432lb5m7oCoosQx6ERXtNcvHfen74vzwhH/VvCpA9HTz9vVsR6SHURjovxnzyuiGiah1ISdYvoZaEOJK3un8lbDqptdKmH9eigvEFeq3psU6NrF8sGMpRKGLfkN1PSxpFp+8EGvMBdCnmZjnbrpbvTfhiJ4RpLDtxDh6ac6GwVWnAioZbI6tiyKP8tSgjibqisBnUYEF9nN/tDxxHv9oS+sQXy+oS/8U+p74d5g9TpquA7UfZKPv5eR7997T4zP29Tz5f/iZeUWhXRrJfxsV5HYbmziAXrLOmJnzbYIMufZd1NPJDBScP0SH+a8ddN51LiFAjTJs6A+7C7lE1oXMhDNa4nRt9Dva2Ib/2PyJ38NMc+qu/XaH8PmPEM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
