travis:
  secure:
    BINSTAR_TOKEN: nPGofUHvg/0WqwxqZl9tVz5vwLFQplEubGV2zHsVj5RM4tScqdakWoBtgAtat27vCZvEvdFH4jqD8h2weitf8AmfCuzWKKLAFrccoGozz0v67P+FnBzauW579JZArp5M2f9WgSBCWaC7MEsbtVJpzeBH9XNSYi7HqEVQs0M1lZ0LS75ZNwHAw9MURsq8Kz3UrP6Mh0aFlmlAeXnvYsqRv/B5zZS5eSBV07VbF05ojp7CbBMMRVy+pCH+0JGrutZwTkGuTTctXsQSGiZcKaOn9Z3nRLI54vOFk3JUTEq2Y6tjcLcFoU3EaPcIkszyP64QsKts7arEakWdfhZq5p29DuK7+F7/CMTSKCqj3xKU3xMXPqGiFy5b2hKv6u9bBPcOt3qZoz3CAgnotzeO39n+35eszMhs8mvHB1EWk4BJRuLcY4IFPoumUL/t28EwZTUOSb1ZbPJpAU2iUNftC5rK/q4nAzRQfV9dC8fx0dILpTjBnV5uZnriyqV92cs5t2F8CE/2b5we1mCEwhzT1nAXg947CmxNcArMNCOSSsaUe2IvYBjciL4LqFzcvC8fu6DQimKwTKI9k8Dmn/83uGfyXitLItX+Ykow+trfGgqbutaVuSleXLlZtZQ4rxXExyQvMOCzZt9tv+JMKPtZ1pehhm9kmlda/+AQG1MDdsG+vgM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
