travis:
  secure:
    BINSTAR_TOKEN: i43jgFABzmw6ZeeuEd8xGZHtVK9W4/94AjhdBEBw51r+2hkwUp+b3QYfYSNsfaGqsmUA7YgC612eX6Tb0PEVmVZT8sTEnh/OBjiD2j1YndpFBX9RG309IJYgD0ufMvKArXULtGzoGm+xPTbCFqdNLJf5HpinT4zJQuyf+Xwze3B2B8W2zp9evuwxXL4OUGTyFpNELHPwZrWDi9gy0hFLNA3WcOTA/xLPWJOhPcBwkor9rHsD29fZApNYmCwGLRNlIA0SCZFcO7B4t8fOZ6Z/nAn9KI8cmPVX7z7ZUPP0yh/gh3OascHiId9bsU23mcZspHaAH+dqwi5oHBz2HeOFIRDM8NjIWmhjnlDH8qaDIrErY8cufBPUjuyRa9l4sZReppd5yfMYLEfRbBy4tfwN/9EMRl0EvUbxDMNS06XEFZ8e/IZO3RUO/ziQVwlhnPDhQoueJ6G7vN7vmY0kqR5a1QLp/tuMxV2OVjaL0pH3uJauGHUZC3aPhGh455KRC8dDllyO1zVb9Bog2UdoOLiL+dbFVHjT0z56RBxerzsLqq7aHz182cwETLNyL5Eaq6oinOTjBze5AbqRcW22CWxsw5Rw80OppAedEXExc4I5Q9f4jYuE42h1VVwl8O3Z31Ldj+0ewPoiTHgVTiupKwdnNe4sp0SmqJTTdBD6ThtqnOE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
