travis:
  secure:
    BINSTAR_TOKEN: jTnjS7SrV4gfVHFpovaOpP9uIBrdERCm9fuWbqEo0KCw60+gw7RWguLFge7Z2ndwxo2IkGpNkd98G+wVi/FsfVVsSAXRVzoE5xX6q7VRK9g2iGHDFK9Qcses773kBeq4q4UjzU13GZaraGI6JD70yK8TNmtIDcvRkI2z84y1qOW5p2e1ZAEbXc9Jecf3tx+EW2DbTLwDuSNk7mSBRgvJa1BLXcNYIh86+h08ebu2jYHYFN/GYnVJCZ8zXTodZEKAsRDZ08/8DqTcNb3tNjuE7a8S1Rn9+Cf1xe9zAFa7gJEAXNM0IFOqDx1tAypFORGgR49RP1jlyf+Cn+BHw+v32S1nSd6THP5Y07U1wFq+4Is8pNAkLdhaUL3Ap9DY4IbvOJIDZ+N6+b8gJhORo7bw3O+X7mgrMlQDXZM+tX1XX/0kuYLv4r8UUDhzipiuAuVUO3Nvbj6ZaSOv136P+C1LLeu9DMkG5eBSLX3g1JNjVa6/Th7MCRqPXD3rwy4i6avzy8ks3jV01hcppmXQQM1rflKT+yM6AMBJ8IR8loOvvKlxU7bJkmPUQP1ChihVquNxZlmbtl8q5SddU8+nStTOQryAfMerI0PHs3kFE9Nh5iBZxsJny/6tbwvmoN66lfDK9/64pEVjswFenTcy738m/ZcsmybwO9tV7odj2iIDijU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
